### ISSUE TITLE
Vendor chests added in fishing Creation are looted

### ISSUE THREAD

**Issue by Lywzc** [SteveTownsend/SmartHarvestSE#403]
Which is not supposed to happen.

**Comment by SteveTownsend** [comment]
Added a check for LVLI record specific to these CONT records

**Comment by SteveTownsend** [comment]
Not any more. Blacklisted these and many others from my Load Order. It's an endless list, unfortunately, because MAs don't follow the vanilla data model for Merchant Chests.
<img width="522" alt="image" src="https://github.com/SteveTownsend/SmartHarvestSE/assets/14825099/0164c4ed-9bfe-41e3-803b-39f6b6dd65aa">

**Comment by SteveTownsend** [comment]
The new additions from my LO are all working as planned
<img width="846" alt="image" src="https://github.com/SteveTownsend/SmartHarvestSE/assets/14825099/b6cfbf52-ccd8-45d2-97d0-77af2dc2eb24">
